from functools import reduce


class Solution:
    """
    https://leetcode.com/problems/find-the-difference/

    Given two strings s and t which consist of only lowercase letters.

    String t is generated by random shuffling string s and then add one
      more letter at a random position.

    Find the letter that was added in t.

    Example:

      Input:
      s = "abcd"
      t = "abcde"

      Output:
      e

      Explanation:
      'e' is the letter that was added.
    """

    @staticmethod
    def findTheDifference(s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """

        # seems faster to use a list comprehension as the second arg
        # also seems faster to use lambda vs operator.xor (no import?)
        return chr(reduce(lambda a, b: a ^ b, [ord(c) for c in s + t]))
